# Generated by Django 5.2.4 on 2025-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreendimentos', to='clientes.cliente')),
            ],
        ),
    ]
