services:
  - type: web
    name: mandacaru-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: changeme-123
      - key: DEBUG
        value: False
