# Generated by Django 5.2.4 on 2025-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='cep',
            field=models.CharField(default='00000-000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='cidade',
            field=models.CharField(default='cidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='endereco',
            field=models.CharField(default='endereço', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='estado',
            field=models.CharField(default='UF', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='descricao',
            field=models.TextField(blank=True, default='Descrição'),
            preserve_default=False,
        ),
    ]
