# Generated by Django 5.2.4 on 2025-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
