# Generated by Django 5.2.4 on 2025-07-07 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagar', 'Conta a Pagar'), ('receber', 'Conta a Receber')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Transferência', 'Transferência'), ('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão')], max_length=20)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('tipo_despesa', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
            ],
        ),
        migrations.DeleteModel(
            name='Lancamento',
        ),
    ]
