# Generated by Django 5.2.4 on 2025-07-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('financeiro.contafinanceira',),
        ),
    ]
