# Generated by Django 5.2.4 on 2025-01-14 15:30

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_snapshot', models.DateField(default=datetime.date.today, unique=True)),
                ('total_equipamentos', models.IntegerField(default=0)),
                ('equipamentos_operacionais', models.IntegerField(default=0)),
                ('equipamentos_manutencao', models.IntegerField(default=0)),
                ('equipamentos_parados', models.IntegerField(default=0)),
                ('equipamentos_nr12_ativos', models.IntegerField(default=0)),
                ('checklists_pendentes', models.IntegerField(default=0)),
                ('checklists_concluidos', models.IntegerField(default=0)),
                ('checklists_com_problemas', models.IntegerField(default=0)),
                ('manutencoes_vencidas', models.IntegerField(default=0)),
                ('manutencoes_proximas', models.IntegerField(default=0)),
                ('alertas_criticos', models.IntegerField(default=0)),
                ('alertas_ativos', models.IntegerField(default=0)),
                ('contas_vencidas', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('contas_a_vencer', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('faturamento_mes', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('produtos_estoque_baixo', models.IntegerField(default=0)),
                ('movimentacoes_estoque', models.IntegerField(default=0)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de KPIs',
                'verbose_name_plural': 'Snapshots de KPIs',
                'ordering': ['-data_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='AlertaDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15, choices=[
                    ('EQUIPAMENTO', 'Equipamento'),
                    ('CHECKLIST', 'Checklist'),
                    ('MANUTENCAO', 'Manutenção'),
                    ('FINANCEIRO', 'Financeiro'),
                    ('ESTOQUE', 'Estoque'),
                    ('SISTEMA', 'Sistema'),
                ])),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(max_length=10, choices=[
                    ('BAIXA', 'Baixa'),
                    ('MEDIA', 'Média'),
                    ('ALTA', 'Alta'),
                    ('CRITICA', 'Crítica'),
                ])),
                ('link_acao', models.URLField(blank=True, help_text="Link para ação do alerta")),
                ('icone', models.CharField(max_length=50, blank=True, help_text="Ícone do alerta")),
                ('ativo', models.BooleanField(default=True)),
                ('exibir_ate', models.DateTimeField(null=True, blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta do Dashboard',
                'verbose_name_plural': 'Alertas do Dashboard',
                'ordering': ['-prioridade', '-criado_em'],
            },
        ),
    ]