# Generated by Django 5.2.4 on 2025-07-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaDashboard',
        ),
        migrations.DeleteModel(
            name='KPISnapshot',
        ),
    ]
