# Generated by Django 5.2.4 on 2025-07-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('descricao', models.TextField()),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='equipamentos.equipamento')),
            ],
        ),
    ]
