# Generated by Django 5.2.4 on 2025-07-06 19:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicomanutencao',
            name='custo_estimado',
        ),
        migrations.AddField(
            model_name='historicomanutencao',
            name='horimetro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='historicomanutencao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicomanutencao',
            name='proxima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicomanutencao',
            name='tecnico_responsavel',
            field=models.CharField(default='tecnico', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicomanutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='equipamentos.equipamento'),
        ),
    ]
