# Generated by Django 5.2.4 on 2025-07-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(default='Rua desconhecida', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(default='cidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(default='Nome da Empresa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(default='UF', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreendimentos', to='clientes.cliente')),
            ],
        ),
    ]
