# Generated by Django 5.2.4 on 2025-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_nome_cliente_bairro_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='uf',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='municipio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
