# Generated by Django 5.2.4 on 2025-07-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_empreendimento_cliente_and_more'),
        ('equipamentos', '0002_alter_equipamento_empreendimento'),
        ('orcamentos', '0002_alter_orcamento_empreendimento'),
        ('ordens_servico', '0002_alter_ordemservico_empreendimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empreendimento',
        ),
    ]
