# Generated by Django 5.2.4 on 2025-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_remove_equipamento_ano_remove_equipamento_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='horimetro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
