# Generated by Django 5.2.4 on 2025-07-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_add_campos_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='localizacao',
        ),
    ]
