# Generated by Django 5.2.4 on 2025-07-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_equipamento_categoria_cnh_necessaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
    ]
