# Generated by Django 5.2.4 on 2025-07-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_servico', models.TextField()),
                ('data_execucao', models.DateField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('criado_via_bot', models.BooleanField(default=False)),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.orcamento')),
            ],
        ),
    ]
