# Generated by Django 5.2.4 on 2025-07-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0001_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao_servico', models.TextField()),
                ('deslocamento_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=6)),
                ('custo_total_deslocamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento')),
                ('equipamentos', models.ManyToManyField(to='equipamentos.equipamento')),
            ],
        ),
    ]
