# Generated by Django 5.2.4 on 2025-07-09 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0003_equipamento_horimetro_equipamento_marca_and_more'),
        ('orcamentos', '0002_remove_orcamento_descricao_remove_orcamento_valor_and_more'),
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='criado_via_bot',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_execucao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao_servico',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='equipamentos.equipamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servico', to='orcamentos.orcamento'),
        ),
    ]
