# Generated by Django 5.2.4 on 2025-07-17 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('funcao', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH'), ('CTPS', 'Carteira de Trabalho')], default='CPF', max_length=10)),
                ('numero_documento', models.CharField(max_length=50)),
                ('cnh_numero', models.CharField(blank=True, max_length=20)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5)),
                ('cnh_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='operadores/qrcodes/')),
                ('qr_code_data', models.CharField(editable=False, max_length=100, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nome'],
            },
        ),
    ]
