# Generated by Django 5.2.4 on 2025-07-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
        ('equipamentos', '0011_equipamento_categoria_cnh_necessaria_and_more'),
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'ordering': ['nome'], 'permissions': [('can_use_telegram_bot', 'Pode usar bot do Telegram'), ('can_supervise_operators', 'Pode supervisionar operadores'), ('can_manage_equipment', 'Pode gerenciar equipamentos')], 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AddField(
            model_name='operador',
            name='ativo_bot',
            field=models.BooleanField(default=True, help_text='Pode usar o bot do Telegram'),
        ),
        migrations.AddField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='clientes_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Clientes que este operador pode atender', related_name='operadores_autorizados', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='operador',
            name='empreendimentos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Empreendimentos onde este operador pode trabalhar', related_name='operadores_autorizados', to='empreendimentos.empreendimento'),
        ),
        migrations.AddField(
            model_name='operador',
            name='equipamentos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Equipamentos que este operador pode operar', related_name='operadores_autorizados', to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='operador',
            name='localizacao_atual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operador',
            name='pode_fazer_checklist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='pode_registrar_abastecimento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='pode_reportar_anomalia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='pode_ver_relatorios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operador',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor responsável por este operador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_supervisionados', to='operadores.operador'),
        ),
        migrations.AddField(
            model_name='operador',
            name='ultimo_acesso_bot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='ultimo_equipamento_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimo_operador', to='equipamentos.equipamento'),
        ),
    ]
