# Generated by Django 5.0.1 on 2025-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0002_alter_operador_options_operador_ativo_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
    ]
