# Generated by Django 5.0.1 on 2025-07-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0003_alter_operador_chat_id_telegram'),
    ]

    operations = [
    ]
