# Generated by Django 5.0.1 on 2025-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0004_auto_20250723_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
