# Generated by Django 5.0.1 on 2025-07-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0005_alter_operador_chat_id_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='qr_code_data',
        ),
        migrations.AlterField(
            model_name='operador',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/operadores/', verbose_name='QR Code do Operador'),
        ),
    ]
