# Generated by Django 5.0.1 on 2025-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0006_remove_operador_qr_code_data_alter_operador_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='qr_code_data',
            field=models.CharField(blank=True, editable=False, help_text='Dados únicos para identificação do QR Code', max_length=100, null=True, unique=True),
        ),
    ]
