# Generated by Django 5.2.4 on 2025-07-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0007_operador_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='ativo_bot',
            field=models.BooleanField(default=True, help_text='Se o operador pode usar o bot Telegram'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, help_text='ID do chat do Telegram', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='qr_code_data',
            field=models.JSONField(blank=True, help_text='Dados do QR Code do operador', null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='ultimo_acesso_bot',
            field=models.DateTimeField(blank=True, help_text='Último acesso via bot Telegram', null=True),
        ),
    ]
