# Generated by Django 5.2.5 on 2025-08-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0009_alter_operador_chat_id_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operador',
            name='qr_code_data',
        ),
    ]
