# Generated by Django 5.2.4 on 2025-08-14 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0003_empreendimento_ativo_empreendimento_data_inicio'),
        ('equipamentos', '0015_add_uuid_field'),
        ('operadores', '0010_remove_operador_qr_code_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='qr_code_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='ativo_bot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, help_text='ID de chat do Telegram', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='clientes_autorizados',
            field=models.ManyToManyField(blank=True, related_name='operadores_autorizados', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF no formato 000.000.000-00')]),
        ),
        migrations.AlterField(
            model_name='operador',
            name='empreendimentos_autorizados',
            field=models.ManyToManyField(blank=True, related_name='operadores_autorizados', to='empreendimentos.empreendimento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='equipamentos_autorizados',
            field=models.ManyToManyField(blank=True, related_name='operadores_autorizados', to='equipamentos.equipamento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores_supervisionados', to='operadores.operador'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='ultimo_acesso_bot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
