# Generated by Django 5.2.4 on 2025-08-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0011_operador_qr_code_data_alter_operador_ativo_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='chat_id_telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
