# Generated by Django 5.2.4 on 2025-07-26 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0004_alter_equipamento_options_equipamento_ativo_nr12_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamentoNR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento NR12',
                'verbose_name_plural': 'Tipos de Equipamentos NR12',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FrequenciaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Frequência de Checklist',
                'verbose_name_plural': 'Frequências de Checklists',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criticidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Criticidade')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='nr12_checklist.tipoequipamentonr12', verbose_name='Tipo de Equipamento')),
            ],
            options={
                'verbose_name': 'Item de Checklist Padrão',
                'verbose_name_plural': 'Itens de Checklist Padrão',
                'ordering': ['ordem', 'item'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistNR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='DIARIA', max_length=10, verbose_name='Frequência do Checklist')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_checklist', models.DateField(verbose_name='Data do Checklist')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite'), ('MADRUGADA', 'Madrugada')], max_length=20, verbose_name='Turno')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15, verbose_name='Status')),
                ('horimetro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Inicial')),
                ('horimetro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro Final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('necessita_manutencao', models.BooleanField(default=False, verbose_name='Necessita Manutenção')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_nr12', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Checklist NR12',
                'verbose_name_plural': 'Checklists NR12',
                'ordering': ['-data_checklist', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Conforme'), ('NOK', 'Não Conforme'), ('NA', 'Não Aplicável'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='checklist/fotos/', verbose_name='Foto Antes')),
                ('foto_depois', models.ImageField(blank=True, null=True, upload_to='checklist/fotos/', verbose_name='Foto Depois')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nr12_checklist.checklistnr12', verbose_name='Checklist')),
                ('item_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nr12_checklist.itemchecklistpadrao', verbose_name='Item Padrão')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Item de Checklist Realizado',
                'verbose_name_plural': 'Itens de Checklist Realizados',
                'ordering': ['item_padrao__ordem'],
            },
        ),
        migrations.CreateModel(
            name='AlertaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Manutenção Preventiva'), ('CORRETIVA', 'Manutenção Corretiva'), ('URGENTE', 'Manutenção Urgente')], max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('NOTIFICADO', 'Notificado'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criticidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Criticidade')),
                ('data_identificacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Identificação')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Notificação')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_manutencao', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('checklist_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nr12_checklist.checklistnr12', verbose_name='Checklist de Origem')),
            ],
            options={
                'verbose_name': 'Alerta de Manutenção',
                'verbose_name_plural': 'Alertas de Manutenção',
                'ordering': ['-data_prevista', '-criticidade'],
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(verbose_name='Data do Abastecimento')),
                ('tipo_combustivel', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('GNV', 'GNV'), ('ELETRICO', 'Elétrico')], max_length=20, verbose_name='Tipo de Combustível')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade (Litros)')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('valor_por_litro', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Valor por Litro (R$)')),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro')),
                ('local_abastecimento', models.CharField(blank=True, max_length=200, verbose_name='Local do Abastecimento')),
                ('posto_fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Posto/Fornecedor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='abastecimentos/comprovantes/', verbose_name='Foto do Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_checklist', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento'],
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anomalia', models.CharField(max_length=20, unique=True, verbose_name='Número da Anomalia')),
                ('data_identificacao', models.DateTimeField(verbose_name='Data de Identificação')),
                ('tipo', models.CharField(choices=[('MECANICA', 'Mecânica'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('PNEUMATICA', 'Pneumática'), ('ESTRUTURAL', 'Estrutural'), ('SEGURANCA', 'Segurança'), ('OPERACIONAL', 'Operacional'), ('OUTRAS', 'Outras')], max_length=20, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica - Parar Operação')], max_length=10, verbose_name='Severidade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('componente_afetado', models.CharField(blank=True, max_length=200, verbose_name='Componente Afetado')),
                ('horimetro_deteccao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro na Detecção')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('EM_REPARO', 'Em Reparo'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('RESOLVIDA', 'Resolvida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('solucao_aplicada', models.TextField(blank=True, verbose_name='Solução Aplicada')),
                ('foto_anomalia', models.ImageField(blank=True, null=True, upload_to='anomalias/fotos/', verbose_name='Foto da Anomalia')),
                ('foto_reparo', models.ImageField(blank=True, null=True, upload_to='anomalias/reparos/', verbose_name='Foto do Reparo')),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado (R$)')),
                ('custo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Real (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('identificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_identificadas', to=settings.AUTH_USER_MODEL, verbose_name='Identificado por')),
                ('responsavel_reparo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_reparadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Reparo')),
                ('checklist_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nr12_checklist.checklistnr12', verbose_name='Checklist de Origem')),
            ],
            options={
                'verbose_name': 'Anomalia',
                'verbose_name_plural': 'Anomalias',
                'ordering': ['-data_identificacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoHorimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(verbose_name='Data do Registro')),
                ('horimetro_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horímetro Anterior')),
                ('horimetro_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horímetro Atual')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Horas Trabalhadas')),
                ('origem', models.CharField(choices=[('CHECKLIST', 'Checklist NR12'), ('ABASTECIMENTO', 'Abastecimento'), ('ANOMALIA', 'Registro de Anomalia'), ('MANUTENCAO', 'Manutenção'), ('MANUAL', 'Atualização Manual')], max_length=50, verbose_name='Origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_horimetro', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Horímetro',
                'verbose_name_plural': 'Histórico de Horímetros',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemchecklistpadrao',
            unique_together={('tipo_equipamento', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemchecklistrealizado',
            unique_together={('checklist', 'item_padrao')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistnr12',
            unique_together={('equipamento', 'data_checklist', 'turno')},
        ),
    ]