# Generated by Django 5.2.4 on 2025-07-13 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_remove_equipamento_tipo_equipamento_categoria'),
        ('nr12_checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Abastecimento')),
                ('tipo_combustivel', models.CharField(choices=[('DIESEL', 'Diesel'), ('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('GNV', 'GNV'), ('ELETRICO', 'Elétrico')], max_length=20, verbose_name='Tipo de Combustível')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade (Litros)')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('valor_por_litro', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Valor por Litro (R$)')),
                ('horimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro')),
                ('local_abastecimento', models.CharField(blank=True, max_length=200, verbose_name='Local do Abastecimento')),
                ('posto_fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Posto/Fornecedor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='abastecimentos/comprovantes/', verbose_name='Foto do Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-data_abastecimento'],
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anomalia', models.CharField(max_length=20, unique=True, verbose_name='Número da Anomalia')),
                ('data_identificacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Identificação')),
                ('tipo', models.CharField(choices=[('MECANICA', 'Mecânica'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('PNEUMATICA', 'Pneumática'), ('ESTRUTURAL', 'Estrutural'), ('SEGURANCA', 'Segurança'), ('OPERACIONAL', 'Operacional'), ('OUTRAS', 'Outras')], max_length=20, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica - Parar Operação')], max_length=10, verbose_name='Severidade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('componente_afetado', models.CharField(blank=True, max_length=200, verbose_name='Componente Afetado')),
                ('horimetro_deteccao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro na Detecção')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('EM_REPARO', 'Em Reparo'), ('AGUARDANDO_PECA', 'Aguardando Peça'), ('RESOLVIDA', 'Resolvida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('solucao_aplicada', models.TextField(blank=True, verbose_name='Solução Aplicada')),
                ('foto_anomalia', models.ImageField(blank=True, null=True, upload_to='anomalias/fotos/', verbose_name='Foto da Anomalia')),
                ('foto_reparo', models.ImageField(blank=True, null=True, upload_to='anomalias/reparos/', verbose_name='Foto do Reparo')),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Estimado (R$)')),
                ('custo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Real (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nr12_checklist.checklistnr12', verbose_name='Checklist de Origem')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('identificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_identificadas', to=settings.AUTH_USER_MODEL, verbose_name='Identificado por')),
                ('responsavel_reparo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_reparadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Reparo')),
            ],
            options={
                'verbose_name': 'Anomalia',
                'verbose_name_plural': 'Anomalias',
                'ordering': ['-data_identificacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoHorimetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro')),
                ('horimetro_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horímetro Anterior')),
                ('horimetro_atual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horímetro Atual')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Horas Trabalhadas')),
                ('origem', models.CharField(choices=[('CHECKLIST', 'Checklist NR12'), ('ABASTECIMENTO', 'Abastecimento'), ('ANOMALIA', 'Registro de Anomalia'), ('MANUTENCAO', 'Manutenção'), ('MANUAL', 'Atualização Manual')], max_length=50, verbose_name='Origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_horimetro', to='equipamentos.equipamento', verbose_name='Equipamento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Horímetro',
                'verbose_name_plural': 'Histórico de Horímetros',
                'ordering': ['-data_registro'],
            },
        ),
    ]
