# Generated by Django 5.2.4 on 2025-07-26 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data_abastecimento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Abastecimento'),
        ),
        migrations.AlterField(
            model_name='anomalia',
            name='data_identificacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Identificação'),
        ),
        migrations.AlterField(
            model_name='historicohorimetro',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Registro'),
        ),
    ]
