# Generated by Django 5.2.4 on 2025-07-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_equipamento_categoria_cnh_necessaria_and_more'),
        ('nr12_checklist', '0002_abastecimento_anomalia_historicohorimetro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_checklist', to='equipamentos.equipamento', verbose_name='Equipamento'),
        ),
    ]
