# Generated by Django 5.2.4 on 2025-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12_checklist', '0002_alter_abastecimento_data_abastecimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamentonr12',
            name='categoria',
            field=models.CharField(blank=True, default='Geral', max_length=100, verbose_name='Categoria'),
        ),
    ]
