# Generated by Django 5.2.4 on 2025-07-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nr12_checklist', '0005_alter_frequenciachecklist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistnr12',
            name='frequencia',
            field=models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='DIARIA', max_length=10, verbose_name='Frequência do Checklist'),
        ),
    ]
