# Generated by Django 5.2.4 on 2025-07-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='empreendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento'),
            preserve_default=False,
        ),
    ]
