# Generated by Django 5.2.4 on 2025-07-10 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_horimetro_equipamento_marca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['nome'], 'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ativo_nr12',
            field=models.BooleanField(default=True, verbose_name='Ativo para NR12'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 10, 21, 50, 22, 715072, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='frequencia_checklist',
            field=models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='DIARIO', max_length=10, verbose_name='Frequência do Checklist'),
        ),
    ]
