# Generated by Django 5.2.4 on 2025-07-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
        ('equipamentos', '0004_alter_equipamento_options_equipamento_ativo_nr12_and_more'),
        ('nr12_checklist', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo_nr12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nr12_checklist.tipoequipamentonr12', verbose_name='Tipo NR12'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento', verbose_name='Empreendimento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='horimetro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Horímetro'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
