# Generated by Django 5.2.4 on 2025-07-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_categoriaequipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='equipamentos.categoriaequipamento', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
