# ================================================================
# CRIAR: backend/apps/equipamentos/migrations/0010_add_status_fields.py
# Execute: python manage.py makemigrations equipamentos
# ================================================================

# Generated by Django 5.2.4 on 2025-01-14 16:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_remove_equipamento_tipo_equipamento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='horimetro_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horímetro Atual'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='proxima_manutencao_preventiva',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção Preventiva'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('PARADO', 'Parado'), ('INATIVO', 'Inativo')], default='OPERACIONAL', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status_operacional',
            field=models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('MANUTENCAO', 'Em Manutenção'), ('PARADO', 'Parado'), ('INATIVO', 'Inativo')], default='OPERACIONAL', max_length=15, verbose_name='Status Operacional'),
        ),
    ]