# Generated by Django 5.2.4 on 2025-07-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_add_status_fields'),
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='categoria_cnh_necessaria',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_inicio_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='localizacao_atual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='nivel_experiencia_minimo',
            field=models.IntegerField(default=0, help_text='Anos mínimos de experiência necessários'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='operador_atual',
            field=models.ForeignKey(blank=True, help_text='Operador que está usando este equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_em_uso', to='operadores.operador'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='requer_cnh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status_operacional',
            field=models.CharField(choices=[('OPERANDO', 'Em Operação'), ('PARADO', 'Parado'), ('MANUTENCAO', 'Em Manutenção'), ('QUEBRADO', 'Quebrado'), ('DISPONIVEL', 'Disponível')], default='DISPONIVEL', max_length=15, verbose_name='Status Operacional'),
        ),
    ]
