# Generated by Django 5.2.4 on 2025-07-19 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0012_equipamento_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='frequencia_checklist',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='frequencias_checklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], max_length=10), blank=True, default=list, size=None, verbose_name='Frequência(s) do Checklist NR12'),
        ),
    ]
