# Generated by Django 5.2.4 on 2025-07-17 21:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_registroabastecimento_origem_combustivel_and_more'),
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_em_estoque', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Quantidade em Estoque (litros)')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quando o estoque chegar a este nível, dispara alerta de reposição.', max_digits=10, verbose_name='Estoque Mínimo (litros)')),
                ('valor_compra', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Preço de Compra (R$/litro)')),
                ('ativo', models.BooleanField(default=True, help_text='Desative para ocultar sem perder histórico.', verbose_name='Registro Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_combustivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_almoxarifado', to='abastecimento.tipocombustivel', verbose_name='Tipo de Combustível')),
            ],
            options={
                'verbose_name': 'Estoque de Combustível',
                'verbose_name_plural': 'Estoques de Combustíveis',
                'ordering': ['tipo_combustivel'],
            },
        ),
    ]
