# Generated by Django 5.2.4 on 2025-07-17 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0011_equipamento_categoria_cnh_necessaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('unidade_medida', models.CharField(default='Litros', max_length=10)),
                ('preco_medio', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Combustível',
                'verbose_name_plural': 'Tipos de Combustível',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('total_litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_horas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_medio_hora', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('preco_medio_litro', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Consumo',
                'verbose_name_plural': 'Relatórios de Consumo',
                'unique_together': {('equipamento', 'periodo_inicio', 'periodo_fim')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_abastecimento', models.DateTimeField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('quantidade_litros', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_litro', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tipo_medicao', models.CharField(choices=[('HORIMETRO', 'Horímetro'), ('QUILOMETRAGEM', 'Quilometragem')], default='HORIMETRO', max_length=15)),
                ('medicao_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicao_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posto_combustivel', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('foto_painel', models.ImageField(blank=True, null=True, upload_to='abastecimentos/paineis/')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='abastecimentos/notas/')),
                ('registrado_via_bot', models.BooleanField(default=False)),
                ('chat_id_telegram', models.CharField(blank=True, max_length=50)),
                ('operador_codigo', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='equipamentos.equipamento')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.tipocombustivel')),
            ],
            options={
                'verbose_name': 'Registro de Abastecimento',
                'verbose_name_plural': 'Registros de Abastecimento',
                'ordering': ['-data_abastecimento'],
                'indexes': [models.Index(fields=['equipamento', 'data_abastecimento'], name='abastecimen_equipam_32b15b_idx'), models.Index(fields=['numero'], name='abastecimen_numero_af4318_idx'), models.Index(fields=['aprovado'], name='abastecimen_aprovad_f9160b_idx')],
            },
        ),
    ]
