# Generated by Django 5.2.4 on 2025-07-17 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroabastecimento',
            name='origem_combustivel',
            field=models.CharField(choices=[('ALMOXARIFADO', 'Almoxarifado'), ('POSTO_EXTERNO', 'Posto Externo')], default='POSTO_EXTERNO', max_length=20, verbose_name='Origem do Combustível'),
        ),
        migrations.AlterField(
            model_name='registroabastecimento',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovou_abastecimentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
