# Generated by Django 5.2.4 on 2025-07-21 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_registroabastecimento_origem_combustivel_and_more'),
        ('equipamentos', '0014_corrigir_frequencia_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatorioconsumo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relatorioconsumo',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='relatorioconsumo',
            name='gerado_por',
        ),
        migrations.AddField(
            model_name='registroabastecimento',
            name='estoque_antes_abastecimento',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estoque registrado antes do abastecimento', max_digits=10, null=True, verbose_name='Estoque Antes (Litros)'),
        ),
        migrations.AddField(
            model_name='registroabastecimento',
            name='estoque_depois_abastecimento',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Estoque após a baixa automática', max_digits=10, null=True, verbose_name='Estoque Depois (Litros)'),
        ),
        migrations.AlterField(
            model_name='registroabastecimento',
            name='origem_combustivel',
            field=models.CharField(choices=[('ALMOXARIFADO', 'Almoxarifado'), ('POSTO_EXTERNO', 'Posto Externo')], default='POSTO_EXTERNO', help_text="Selecione 'Almoxarifado' para baixa automática no estoque", max_length=20, verbose_name='Origem do Combustível'),
        ),
        migrations.AlterField(
            model_name='registroabastecimento',
            name='quantidade_litros',
            field=models.DecimalField(decimal_places=3, help_text='Quantidade que será descontada do estoque se origem for Almoxarifado', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='registroabastecimento',
            index=models.Index(fields=['origem_combustivel'], name='abastecimen_origem__4854b3_idx'),
        ),
        migrations.DeleteModel(
            name='RelatorioConsumo',
        ),
    ]
