# Generated by Django 5.2.4 on 2025-07-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_rename_nome_cliente_bairro_remove_cliente_endereco_and_more'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='rascunho', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.empreendimento')),
                ('equipamentos', models.ManyToManyField(to='equipamentos.equipamento')),
            ],
        ),
    ]
