# Generated by Django 5.2.4 on 2025-07-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '__first__'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento'),
        ),
    ]
