# Generated by Django 5.2.4 on 2025-07-09 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
        ('equipamentos', '0003_equipamento_horimetro_equipamento_marca_and_more'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='os_criada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='empreendimentos.empreendimento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='equipamentos.equipamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Rejeitado')], default='P', max_length=1),
        ),
    ]
