# Generated by Django 5.2.4 on 2025-07-11 11:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('empreendimentos', '0002_remove_empreendimento_localizacao_empreendimento_cep_and_more'),
        ('orcamentos', '0002_remove_orcamento_descricao_remove_orcamento_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='os_criada',
            new_name='aprovado_por_bot',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_deslocamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_vencimento',
            field=models.DateField(default=datetime.datetime(2025, 8, 10, 11, 8, 17, 13054, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='empreendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='empreendimentos.empreendimento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('CONVERTIDO', 'Convertido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almoxarifado.produto')),
            ],
        ),
    ]
